name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: technote-space/can-npm-publish-action@v1
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    - run: npm i -g npm@latest
    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: npmjs.org npm publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        registry: https://registry.npmjs.org
        access: public
    - run: npm pkg set "name=@${{ GITHUB.REPOSITORY }}"
    - name: github.com npm publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ GITHUB.TOKEN }}
        registry: https://npm.pkg.github.com
        access: public
